# 육상선수 종목별 기록 데이터

In [1]:
import numpy as np

A = np.array([
              [3.73, 1.86, 15.8, 4.05, 7.27, 45.66, 34.92 ],
              [3.57, 1.80, 16.23, 2.96, 6.71, 42.56, 37.31],
              [3.22, 1.83, 14.20, 3.51, 6.68, 44.54, 39.23],
              [2.81, 1.80, 15.23, 2.69, 6.25, 42.78, 31.19],
              [2.91, 1.74, 14.76, 2.68, 6.32, 47.46, 35.53],
              [2.67, 1.83, 13.50, 1.96, 6.33, 42.82, 37.64]
])

# 허들 종목 기록 데이터 및 통계지표

In [10]:
print('허들 종목 기록 데이터')
hurdle = A[:,0]
print(hurdle)
print(f'평균:{np.mean(hurdle):.3f}')
print(f'n-1분산:{np.var(hurdle, ddof=1):.3f}') #자유도 (n-ddof)
print(f'분산:{np.var(hurdle):.3f}')

#print(f'표준편차:{np.sqrt(np.var(hurdle)):.3f}')
print(f'n-1표준편차:{np.std(hurdle, ddof=1):.3f}')
print(f'표준편차:{np.std(hurdle):.3f}')

허들 종목 기록 데이터
[3.73 3.57 3.22 2.81 2.91 2.67]
평균:3.152
n-1분산:0.184
분산:0.154
n-1표준편차:0.429
표준편차:0.392


# 공분산 행렬

In [12]:
np.set_printoptions(suppress=True, precision=3)

In [13]:
print(['Covariance Metrix'])
B = np.cov(A, rowvar=False) 
#rowvar: True ; 행이 변수를 나타내며, 열은 각 변수의 관측치를 나타낸다.
#rowvar: False ; 행이 각 변수의 관측치를 나타내며,열은 변수를 나타낸다.
print(B)
# 대각선 -- > 각 종목에 대한 분산값


['Covariance Metrix']
[[ 0.184  0.007  0.325  0.262  0.151  0.109  0.222]
 [ 0.007  0.002 -0.001  0.014  0.01  -0.029  0.022]
 [ 0.325 -0.001  1.028  0.388  0.199 -0.026 -1.06 ]
 [ 0.262  0.014  0.388  0.528  0.244  0.524  0.078]
 [ 0.151  0.01   0.199  0.244  0.148  0.157  0.21 ]
 [ 0.109 -0.029 -0.026  0.524  0.157  3.884  0.085]
 [ 0.222  0.022 -1.06   0.078  0.21   0.085  7.871]]


In [14]:
A = np.array([
              [3.73, 1.86, 15.8, 4.05, 7.27, 45.66, 34.92 ],
              [3.57, 1.80, 16.23, 2.96, 6.71, 42.56, 37.31],
              [3.22, 1.83, 14.20, 3.51, 6.68, 44.54, 39.23],
              [2.81, 1.80, 15.23, 2.69, 6.25, 42.78, 31.19],
              [2.91, 1.74, 14.76, 2.68, 6.32, 47.46, 35.53],
              [2.67, 1.83, 13.50, 1.96, 6.33, 42.82, 37.64]
])

In [19]:
print('열평균:',[np.mean(A[:,0]),np.mean(A[:,1]),np.mean(A[:,2]),np.mean(A[:,3]),np.mean(A[:,4]),np.mean(A[:,5]),np.mean(A[:,6])] )

열평균: [3.1516666666666673, 1.8099999999999998, 14.953333333333335, 2.9749999999999996, 6.593333333333334, 44.303333333333335, 35.97]


In [23]:
X = A - np.mean(A, axis=0)
print(X)

[[ 0.578  0.05   0.847  1.075  0.677  1.357 -1.05 ]
 [ 0.418 -0.01   1.277 -0.015  0.117 -1.743  1.34 ]
 [ 0.068  0.02  -0.753  0.535  0.087  0.237  3.26 ]
 [-0.342 -0.01   0.277 -0.285 -0.343 -1.523 -4.78 ]
 [-0.242 -0.07  -0.193 -0.295 -0.273  3.157 -0.44 ]
 [-0.482  0.02  -1.453 -1.015 -0.263 -1.483  1.67 ]]


In [29]:
print(X.T)

[[ 0.578  0.418  0.068 -0.342 -0.242 -0.482]
 [ 0.05  -0.01   0.02  -0.01  -0.07   0.02 ]
 [ 0.847  1.277 -0.753  0.277 -0.193 -1.453]
 [ 1.075 -0.015  0.535 -0.285 -0.295 -1.015]
 [ 0.677  0.117  0.087 -0.343 -0.273 -0.263]
 [ 1.357 -1.743  0.237 -1.523  3.157 -1.483]
 [-1.05   1.34   3.26  -4.78  -0.44   1.67 ]]


In [30]:
print(X.T@X)

[[ 0.921  0.037  1.624  1.31   0.756  0.544  1.111]
 [ 0.037  0.008 -0.004  0.068  0.052 -0.145  0.111]
 [ 1.624 -0.004  5.14   1.941  0.997 -0.131 -5.299]
 [ 1.31   0.068  1.941  2.641  1.218  2.62   0.392]
 [ 0.756  0.052  0.997  1.218  0.741  0.786  1.05 ]
 [ 0.544 -0.145 -0.131  2.62   0.786 19.421  0.426]
 [ 1.111  0.111 -5.299  0.392  1.05   0.426 39.357]]


In [31]:
len(X)

6

In [28]:
print('Covariance Matrix')
cov = (X.T@X)/(len(X)-1)
print(cov)

Covariance Matrix
[[ 0.184  0.007  0.325  0.262  0.151  0.109  0.222]
 [ 0.007  0.002 -0.001  0.014  0.01  -0.029  0.022]
 [ 0.325 -0.001  1.028  0.388  0.199 -0.026 -1.06 ]
 [ 0.262  0.014  0.388  0.528  0.244  0.524  0.078]
 [ 0.151  0.01   0.199  0.244  0.148  0.157  0.21 ]
 [ 0.109 -0.029 -0.026  0.524  0.157  3.884  0.085]
 [ 0.222  0.022 -1.06   0.078  0.21   0.085  7.871]]


In [ ]:
np.array()