# 공분산 행렬 구하기

In [1]:
import numpy as np
np.set_printoptions(suppress=True, precision=2)

In [26]:
x = [[177.7, 68.1, 91.8], [168, 60.2, 89.3], [165.3, 49.1, 84.9], [159.1, 42, 86.3], [176.4, 73.3, 93.8],
     [176, 57.2, 92.5], [170, 59.8, 89.8], [164.6, 51.6, 88.5], [174.4, 70.2, 91.7], [174.8, 58.8, 91.6]]
X = np.array(x)
print(X)

[[177.7  68.1  91.8]
 [168.   60.2  89.3]
 [165.3  49.1  84.9]
 [159.1  42.   86.3]
 [176.4  73.3  93.8]
 [176.   57.2  92.5]
 [170.   59.8  89.8]
 [164.6  51.6  88.5]
 [174.4  70.2  91.7]
 [174.8  58.8  91.6]]


In [27]:
print(f'키 컬럼 분산 : {np.var(X[:,0],ddof=1):.2f}')

키 컬럼 분산 : 38.75


In [28]:
np.mean(X,axis=0)

array([170.63,  59.03,  90.02])

In [29]:
# 데이터 분포의 중심을 중심축으로 이동시키기 위해 행렬의 각 열들의 평균값을 0으로 맞춘다.
X = X- np.mean(X, axis=0)
print(X)

[[  7.07   9.07   1.78]
 [ -2.63   1.17  -0.72]
 [ -5.33  -9.93  -5.12]
 [-11.53 -17.03  -3.72]
 [  5.77  14.27   3.78]
 [  5.37  -1.83   2.48]
 [ -0.63   0.77  -0.22]
 [ -6.03  -7.43  -1.52]
 [  3.77  11.17   1.68]
 [  4.17  -0.23   1.58]]


In [30]:
print('공분산 행렬')
# 공분산구하기
cov = X.T @ X / len(X)-1
print(cov)

공분산 행렬
[[33.87 45.83 13.2 ]
 [45.83 84.99 19.84]
 [13.2  19.84  6.19]]


# np.cov 함수와 결과 비교

In [31]:
np_cov = np.cov(X,rowvar=False)
# 행을 변수로 보고 열을 관측치로 보고있음
print(np_cov)

[[38.75 52.03 15.78]
 [52.03 95.54 23.16]
 [15.78 23.16  7.98]]


# 고유값, 고유백터 행렬 구하기

In [40]:
eigenvalue, eigenvector = np.linalg.eig(cov) # 고유값과 고유백터행렬을 튜플로 반환해줌

In [41]:
print(f'고유값: {eigenvalue} \n고유백터 행렬(V):\n{eigenvector}') 

고유값: [117.01   7.23   0.8 ] 
고유백터 행렬(V):
[[-0.5  -0.82 -0.28]
 [-0.84  0.54 -0.07]
 [-0.21 -0.2   0.96]]


In [43]:
print('고유값 대각행렬(lambda)')
eig_matrix = np.eye(3) * eigenvalue
print(eig_matrix)

고유값 대각행렬(lambda)
[[117.01   0.     0.  ]
 [  0.     7.23   0.  ]
 [  0.     0.     0.8 ]]


In [46]:
print('첫 번째 고유백터와 두 번째 고유 백터와의 내적')
c = (eigenvector[:,0].T) @ (eigenvector[:,1])
print(np.round(c,4))
# 두 백터가 서로 직교하면 내적 값이 0이 된다.
# PC2(두번째로 큰 분산을 나타내는 값) 는 PC1과(가장 큰 분산을 나타내는 값) --> 직교한다

첫 번째 고유백터와 두 번째 고유 백터와의 내적
-0.0


In [49]:
print('고유값 분해를 통한 공분산 행렬을 계산')
A = eigenvector@eig_matrix@np.linalg.inv(eigenvector)
# np.linalg.inv --> inv --> 역행렬
print(A)

고유값 분해를 통한 공분산 행렬을 계산
[[33.87 45.83 13.2 ]
 [45.83 84.99 19.84]
 [13.2  19.84  6.19]]


In [50]:
print(cov)

[[33.87 45.83 13.2 ]
 [45.83 84.99 19.84]
 [13.2  19.84  6.19]]


# 첫 번째 주성분 (PC1) 구하기

In [53]:
X

array([[  7.07,   9.07,   1.78],
       [ -2.63,   1.17,  -0.72],
       [ -5.33,  -9.93,  -5.12],
       [-11.53, -17.03,  -3.72],
       [  5.77,  14.27,   3.78],
       [  5.37,  -1.83,   2.48],
       [ -0.63,   0.77,  -0.22],
       [ -6.03,  -7.43,  -1.52],
       [  3.77,  11.17,   1.68],
       [  4.17,  -0.23,   1.58]])

In [57]:
print(eigenvector[:,0].T)

[-0.5  -0.84 -0.21]


In [59]:
print(X.T)

[[  7.07  -2.63  -5.33 -11.53   5.77   5.37  -0.63  -6.03   3.77   4.17]
 [  9.07   1.17  -9.93 -17.03  14.27  -1.83   0.77  -7.43  11.17  -0.23]
 [  1.78  -0.72  -5.12  -3.72   3.78   2.48  -0.22  -1.52   1.68   1.58]]


In [58]:
pc1 = eigenvector[:,0].T@X.T #열이 독립변수, 행이 관측치이기 떄문
print(pc1) #10명에 대한 데이터
# 백터 v1에 사형을 해서 첫번째 사람 데이터가 어디에 있는지 나타남

[-11.52   0.47  12.08  20.85 -15.68  -1.65  -0.29   9.57 -11.63  -2.21]


# 공분산을 이용한 주성분 분석

In [64]:
print('PCA를 이용한 차원 축소')
VT = np.array([eigenvector[:,0],eigenvector[:,1]])
print('고유백터 VT - 주성분 두개 선택')
print(VT)
print('고유백터 VT 와 원데이터 XT의 내적')
Z = VT@X.T
print(Z.T)

PCA를 이용한 차원 축소
고유백터 VT - 주성분 두개 선택
[[-0.5  -0.84 -0.21]
 [-0.82  0.54 -0.2 ]]
고유백터 VT 와 원데이터 XT의 내적
[[-11.52  -1.31]
 [  0.47   2.93]
 [ 12.08   0.09]
 [ 20.85   1.1 ]
 [-15.68   2.14]
 [ -1.65  -5.89]
 [ -0.29   0.97]
 [  9.57   1.28]
 [-11.63   2.54]
 [ -2.21  -3.86]]


# PCA 클래스와 결과 비교

In [2]:
from sklearn.decomposition import PCA

In [3]:
x = [[177.7, 68.1, 91.8], [168, 60.2, 89.3], [165.3, 49.1, 84.9], [159.1, 42, 86.3], [176.4, 73.3, 93.8],
     [176, 57.2, 92.5], [170, 59.8, 89.8], [164.6, 51.6, 88.5], [174.4, 70.2, 91.7], [174.8, 58.8, 91.6]]
X = np.array(x)

In [4]:
X

array([[177.7,  68.1,  91.8],
       [168. ,  60.2,  89.3],
       [165.3,  49.1,  84.9],
       [159.1,  42. ,  86.3],
       [176.4,  73.3,  93.8],
       [176. ,  57.2,  92.5],
       [170. ,  59.8,  89.8],
       [164.6,  51.6,  88.5],
       [174.4,  70.2,  91.7],
       [174.8,  58.8,  91.6]])

In [67]:
model = PCA(n_components= 2) #2차원으로 축소
pca = model.fit_transform(X)
print(pca.shape)
print(pca)

(10, 2)
[[-11.53   1.18]
 [  0.49  -2.92]
 [ 12.11  -0.13]
 [ 20.85  -0.91]
 [-15.67  -2.2 ]
 [ -1.7    5.91]
 [ -0.28  -0.98]
 [  9.57  -1.17]
 [-11.61  -2.64]
 [ -2.24   3.86]]


# PCA 가 차지하는 분산 비율 구하기

In [73]:
print(model.explained_variance_ratio_)
# 첫번째 component 의 전체 분산의 93프로를 설명
print(f'분산 합 : {np.sum(model.explained_variance_ratio_):.2f}')
# PC1의 설명력
#   = L1 / (L1+L2+L3)
ratio = (eigenvalue[0]+ eigenvalue[1])/ np.sum(eigenvalue)
# 람다 = 분산의 크기
print(eigenvalue)
print(ratio)

[0.93 0.06]
분산 합 : 0.99
[117.01   7.23   0.8 ]
0.9936004500845471


In [75]:
print(model.components_ )# 고유백터 행렬
print(model.explained_variance_)#고유값

[[-0.5  -0.84 -0.22]
 [ 0.8  -0.54  0.24]]
[132.7    8.31]
