# 잠재 요인 협업 필터링을 통한 영화 추천

## 경사하강법을 이용한 행렬 분해
- 특이값 분해는 NaN(결측치)가 없는 행렬에만 적용할 수 있다.
- 하지만 R행렬(사용자-영화 평점 행렬)은 아직 평점되지 않는 많은 Null값이 있기 때문에 P와 Q 행렬을 일반적인 특이값분해 방식으로 분해할 수 없다. 

### 행렬 분해 로직 함수
- R (m x n ) = P( m x K)* Q.T(K x n)  [m: 유저 수, n : 아이템 수, K: 잠재요인 수] 
    - 즉 , m x n 행렬이 나옴
- P 행렬과 Q행렬을 경사 하강법을 통해 만듦
- R : 사용자 - 아이템 평점 행렬
- P : 사용자 - 잠재요인 행렬 (초기 값은 랜덤 값)
- Q : 잠재요인 - 아이템 행렬 (초기 값은 랜덤 값)
- K : 잠재 요인의 차원 수
- steps: SGD 의 반복 횟수
- learning_rate : 학습률(얼마나 촘촘하게 경사를 타고 내려올 것인지)
- r_lambda : L2 규제 계수

In [13]:
import numpy as np

def matrix_fatorization(R,K, steps= 200, learning_rate = 0.01, r_lambda = 0.01):
    num_users, num_items = R.shape
    np.random.seed(1)
    P = np.random.normal(scale=1./K, size= (num_users, K)) # scale = 표준편차 값
    Q = np.random.normal(scale=1./K, size= (num_items, K)) # scale = 표준편차 값
    
    # R행렬의 값이 >0 (실제 평점이 있는 곳)의 행위치, 열위치, 평점값을 리스트로 저장
    non_zeros = [ (i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] >0 ]
    
    for step in range(steps): #반복 학습의 횟수만큼 돎
        for i,j,r in non_zeros:
            #실제값과 예측값의 차이인 오차 계산
            eij = r - P[i,:]@Q[j,:].T 
            
            #L2 규제가 적용된 손실함수의 미분식
            P[i,:] = P[i,:] + learning_rate*(eij*Q[j,:] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij*P[i,:] - r_lambda*Q[j,:])
    
    return P,Q

### SGD 를 이용한 행렬분해 실습

In [21]:
np.set_printoptions(suppress = True, precision = 3)

In [3]:
R = np.array([[4,np.NaN,np.NaN,2 ,np.NaN],
              [np.NaN,5,np.NaN,3,1],
              [np.NaN, np.NaN, 3, 4,5],
              [5,2,1,2,np.NaN]])
R

array([[ 4., nan, nan,  2., nan],
       [nan,  5., nan,  3.,  1.],
       [nan, nan,  3.,  4.,  5.],
       [ 5.,  2.,  1.,  2., nan]])

In [23]:
P, Q = matrix_fatorization(R,K=5, steps=1000, learning_rate = 0.01, r_lambda= 0.01)
pred_matrix = P@Q.T
print(R)
print(pred_matrix)

[[ 4. nan nan  2. nan]
 [nan  5. nan  3.  1.]
 [nan nan  3.  4.  5.]
 [ 5.  2.  1.  2. nan]]
[[3.993 1.524 1.14  1.995 1.423]
 [4.85  4.977 1.25  2.986 1.003]
 [2.956 1.285 2.991 3.983 4.983]
 [4.973 2.004 0.999 2.    0.938]]


## 사용자-아이템 (영화) 평점 행렬 변환

In [25]:
import pandas as pd

movies = pd.read_csv('./movies.csv')
ratings = pd.read_csv('./ratings.csv')
ratings = ratings[['userId','movieId','rating']]



userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [26]:
ratings_movie = pd.merge(ratings, movies, on= 'movieId')
ratings_movie.head()

userId  movieId  rating             title                                       genres
0       1        1     4.0  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1       5        1     4.0  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
2       7        1     4.5  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
3      15        1     2.5  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
4      17        1     4.5  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy

In [31]:
ratings_matrix = pd.pivot_table(ratings_movie, index = 'userId', columns='title', values = 'rating')
ratings_matrix.head()

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1              NaN  ...                                        NaN
2              NaN  ...                                        NaN
3              NaN  ...                                        NaN
4              NaN  ...                                        NaN
5              NaN  ...                                        NaN

[5 rows x 9719 columns]

## 사용자 - 아이템 평점 행렬 분해 및 예측 평점 행렬 생성
- R_hat = P* Q.T

In [32]:
P,Q = matrix_fatorization(ratings_matrix.values, K=50, steps=200, learning_rate=0.01, r_lambda=0.01)

In [33]:
pred_matrix = P@Q.T

In [34]:
ratings_pred_matrix = pd.DataFrame(pred_matrix, index= ratings_matrix.index, columns= ratings_matrix.columns)

ratings_pred_matrix.head(3)

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1         3.055084  ...                                   0.859474
2         3.170119  ...                                   0.725684
3         2.307073  ...                                   0.396941

[3 rows x 9719 columns]

## 평점을 주지 않은 영화 리스트 반환 함수

In [37]:
ratings_matrix= ratings_matrix.fillna(0)
ratings_matrix.head()

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1              0.0  ...                                        0.0
2              0.0  ...                                        0.0
3              0.0  ...                                        0.0
4              0.0  ...                                        0.0
5              0.0  ...                                        0.0

[5 rows x 9719 columns]

In [42]:
def get_unseen_movies (ratings_matrix, userId):
    user_rating = ratings_matrix.loc[userId]
    
    return user_rating[user_rating==0].index.tolist()

## 특정 사용자의 관람하지 않은 영화에 대한 예측 평점 기반의 추천

In [43]:
def recomn_movie_by_userId(pred_df, userId, unseen_list, top_n=10):
    recomn_movies = pred_df.loc[userId,unseen_list]
    recomn_movies = pred_df.loc[userId,unseen_list].sort_values(ascending = False)[:top_n]
    
    return recomn_movies

In [55]:
unseen_list = get_unseen_movies(ratings_matrix, 9)
recomn_movies= recomn_movie_by_userId(ratings_pred_matrix,9,unseen_list,top_n=10)
recomn_movies

title
Rear Window (1954)                                       5.704612
South Park: Bigger, Longer and Uncut (1999)              5.451100
Rounders (1998)                                          5.298393
Blade Runner (1982)                                      5.244951
Roger & Me (1989)                                        5.191962
Gattaca (1997)                                           5.183179
Ben-Hur (1959)                                           5.130463
Rosencrantz and Guildenstern Are Dead (1990)             5.087375
Big Lebowski, The (1998)                                 5.038690
Star Wars: Episode V - The Empire Strikes Back (1980)    4.989601
Name: 9, dtype: float64

In [56]:
recomn_movies

title
Rear Window (1954)                                       5.704612
South Park: Bigger, Longer and Uncut (1999)              5.451100
Rounders (1998)                                          5.298393
Blade Runner (1982)                                      5.244951
Roger & Me (1989)                                        5.191962
Gattaca (1997)                                           5.183179
Ben-Hur (1959)                                           5.130463
Rosencrantz and Guildenstern Are Dead (1990)             5.087375
Big Lebowski, The (1998)                                 5.038690
Star Wars: Episode V - The Empire Strikes Back (1980)    4.989601
Name: 9, dtype: float64

In [59]:
type(recomn_movies)

pandas.core.series.Series

In [60]:
recomn_movies.values

array([5.705, 5.451, 5.298, 5.245, 5.192, 5.183, 5.13 , 5.087, 5.039,
       4.99 ])

In [58]:
pd.DataFrame(recomn_movies.values, index= recomn_movies.index, columns= ['pred_score'])

pred_score
title                                                         
Rear Window (1954)                                    5.704612
South Park: Bigger, Longer and Uncut (1999)           5.451100
Rounders (1998)                                       5.298393
Blade Runner (1982)                                   5.244951
Roger & Me (1989)                                     5.191962
Gattaca (1997)                                        5.183179
Ben-Hur (1959)                                        5.130463
Rosencrantz and Guildenstern Are Dead (1990)          5.087375
Big Lebowski, The (1998)                              5.038690
Star Wars: Episode V - The Empire Strikes Back ...    4.989601